const produtos = [
  {
    id: 0,
    nome: "Hworang",
    preco: 20,
    stock: 10,
    descript: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imagem: "./img/modelB.png",
  },
  {
    id: 1,
    nome: "Kazuya",
    preco: 50,
    stock: 5,
    descript: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imagem: "./img/modelC.png",
  },
  {
    id: 2,
    nome: "Jin",
    preco: 30,
    stock: 15,
    descript: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imagem: "./img/modelD.png",
  },
  {
    id: 3,
    nome: "King",
    preco: 70,
    stock: 7,
    descript: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imagem: "./img/modelE.png",
  },
  {
    id: 4,
    nome: "Xiaoyu",
    preco: 15,
    stock: 22,
    descript: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imagem: "./img/modelF.png",
  },
  {
    id: 5,
    nome: "Nina",
    preco: 30,
    stock: 20,
    descript: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    imagem: "./img/modelH.png",
  },
];
